schema_version = "1.0.0"
id = "fill_mesh"
version = "1.0.8"
name = "Fill Mesh"
tagline = "An add-on to fix and fill holes on your meshes"
maintainer = "Guillaume Bissieres"
type = "add-on"
website = "https://bissieres.gumroad.com/l/FillMesh"
tracker_url = "https://github.com/GuillaumeBissieres/FillMesh/issues"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-3.0-or-later",
]
